---
services:
  runner:
    image: github-runner-unx:latest
    platform: linux
    deploy:
      mode: replicated
      replicas: 1
    build:
      context: .
      args:
        RUNNER_VERSION: '2.316.0'
    env_file:
      ../.env