---
services:
  runner:
    image: github-runner-win:latest
    platform: windows
    deploy:
      mode: replicated
      replicas: 1
    build:
      context: .
      args:
        RUNNER_VERSION: '2.320.0'
    env_file:
      ../.env